BEGIN
    DBMS_OUTPUT.PUT_LINE('Executing init-user-and-tables.sql script');
END;
/

-- Crear usuario con nombre válido
CREATE USER C##maylcon IDENTIFIED BY maylcon123;
GRANT CONNECT, RESOURCE, DBA TO C##maylcon;

-- Conectar como el nuevo usuario
ALTER SESSION SET CURRENT_SCHEMA = C##maylcon;

-- Crear tabla AuthorEntity
CREATE TABLE Author (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255),
    status VARCHAR2(255)
);

-- Crear tabla LibraryEntity
CREATE TABLE Library (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255),
    category VARCHAR2(255),
    status VARCHAR2(255),
    author_id NUMBER,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES Author(id)
);
/

CREATE OR REPLACE PROCEDURE "C##MAYLCON".get_author_by_name (
    p_author_name IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT a.id, a.name, a.status
    FROM author a
    WHERE a.name LIKE '%' || p_author_name || '%';
END;
/

CREATE OR REPLACE PROCEDURE "C##MAYLCON".get_libraries_by_author (
    p_author_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT l.id, l.name, l.category, l.status
    FROM library l
    INNER JOIN author a
    ON a.id = l.author_Id
    WHERE a.id = p_author_id;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('init-user-and-tables.sql script executed successfully');
END;
/